src/accounts/urls.py
from django.conf.urls import url
from django.urls import path,include
from .views import registerview
from .views import givereview,reviewsview,graphviews,graphsviews,placementviews
from .views import loginview,logoutview

app_name='accounts'

urlpatterns = [
    
    path(r'register/', registerview, name="register"),
    path(r'login/', loginview, name="login"),
    path(r'logout/', logoutview, name="logout"),
    path(r'review/(?p<id>)/', givereview,name="review"),
    path(r'reviews/(?p<colg>)/', reviewsview, name="reviews"),
    path(r'simple.pngs', graphviews,name="graph"),
    path(r'simple.pngs/(?p<colg>)/', graphsviews,name="graphs"),
    path(r'placement.pngs', placementviews,name="placement"),

]

src/src/urls.py
from django.contrib import admin
from accounts.views import func
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', func, name="home"),
    path(r'accounts/', include('accounts.urls', namespace="accounts")),

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
	
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	mobile = models.CharField(max_length=13)
	reg = models.CharField(max_length=10)
	college = models.CharField(max_length=30)
	gender = models.CharField(max_length=6)
	date_created = models.DateTimeField(auto_now=True, auto_now_add=False, null=True)
	rated = models.IntegerField(default=0)

	

	def __str__(self):
		return self.college

	def __unicode__(self):
		return self.college


class inputreviews(models.Model):
	college = models.CharField(max_length=30)
	infrastructure = models.IntegerField(default=0)
	Academics = models.IntegerField(default=0)
	Curricular = models.IntegerField(default=0)
	Placement = models.IntegerField(default=0)
	Hostel = models.IntegerField(default=0)
	No_of_reviews = models.IntegerField(default=0)
	Average = models.IntegerField(default=0)
	

	def __str__(self):
		return self.college
	

class Colleges(models.Model):
    colg_name = models.CharField(max_length=30)
    image = models.ImageField(upload_to="accounts/images",default="")


    def __str__(self):
        return self.colg_name

src/accounts/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django import forms
from .models import Profile

GENDER_CHOICES = [('Male','Male'), ('Female','Female'), ('Others','Others')]
COLLEGE_CHOICES = [
	('NIT Agartala','NIT Agartala'), ('NIT Allahabad','NIT Allahabad'), ('NIT Bhopal','NIT Bhopal'),
	('NIT Calicut','NIT Calicut'), (' NIT Jamshedpur',' NIT Jamshedpur'), ('NIT Kurukshetra','NIT Kurukshetra'),
	('NIT Raipur','NIT Raipur'), ('NIT Surathkal','NIT Surathkal'), ('NIT Tiruchirappalli','NIT Tiruchirappalli'),
	('NIT Warangal','NIT Warangal')]
class RegistrationForm(forms.Form):

	first_name = forms.CharField(label="", widget=forms.TextInput(attrs={'autofocus':'on', 'autocomplete':'off', 'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Surname'}))
	reg = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Registration Number'}))
	#dob = forms.DateField(label="Date of birth", widget=forms.DateInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'YYYY-MM-DD'}))
	#gender = forms.CharField(label='Gender', widget=forms.RadioSelect(choices=GENDER_CHOICES, attrs={'class':'custom-control-inline'}))
	gender= forms.CharField(label='Gender', widget=forms.Select(choices=GENDER_CHOICES))
	college= forms.CharField(label='College', widget=forms.Select(choices=COLLEGE_CHOICES))
	mobile = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Mobile Number'}))
	email = forms.CharField(label="", widget=forms.EmailInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Email address'}))
	username = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Username'}))
	password = forms.CharField(label="", widget=forms.PasswordInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Your Password'}))
	cpassword = forms.CharField(label="", widget=forms.PasswordInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Confirm Password'}))
	
	def clean_email(self):
		email = self.cleaned_data.get("email")
		if len(User.objects.filter(email=email)):
			raise forms.ValidationError("Email Already Registered")

		return email


	def clean_mobile(self):
		mobile = self.cleaned_data.get("mobile")
		try:
			a = int(mobile)
		except:
			raise forms.ValidationError("Incorrect mobile number")
		if len(mobile)!=10:
			raise forms.ValidationError("Incorrect mobile number")
		elif len(Profile.objects.filter(mobile=mobile)):
			raise forms.ValidationError("Mobile Already Registered")

		return mobile

	def clean_username(self):
		username = self.cleaned_data.get("username")
		if len(User.objects.filter(username=username)):
			raise forms.ValidationError("Username already has been taken")

		return username

	def clean_password(self):
		password = self.cleaned_data.get("password")
		if len(password)<6:
			raise forms.ValidationError("Password must be at least 6 characters")

		return password

	def clean_cpassword(self):
		password = self.cleaned_data.get("password")
		cpassword = self.cleaned_data.get("cpassword")
		if password!=cpassword:
			raise forms.ValidationError("Passwords must match")

		return password


class LoginForm(forms.Form):
	username = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','autofocus':'on','class':'form-control', 'placeholder':'Username'}))
	password = forms.CharField(label="", widget=forms.PasswordInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Password'}))

	def clean_username(self):
		username = self.cleaned_data.get("username")
		if len(User.objects.filter(username=username))==0:
			raise forms.ValidationError("Username does not exist")

		return username

	def clean_password(self):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")
		user = authenticate(username=username, password=password)
		if user is None:
			raise forms.ValidationError("Wrong Username or Password")
		return password

src/accounts/views.py
from django.shortcuts import render
from django.contrib import messages
from .forms import RegistrationForm,LoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect,HttpResponse
from .models import Profile
from .models import inputreviews
from .models import Colleges
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
import matplotlib.pyplot as plt 
import numpy as np
import io


from django.contrib.auth import (

	authenticate,
	login,
	logout

	)

def loginview(request):
	form = LoginForm(request.POST or None)
	if request.method =="POST":
		if form.is_valid():
			username = form.cleaned_data.get("username")
			password = form.cleaned_data.get("password")
			print(username,password)
			user = authenticate(username=username, password=password)
			login(request, user)
			return HttpResponseRedirect(reverse("home"))

	context = {
		'form':form 
	}
	return render(request, 'accounts/login.html', context)


@login_required
def logoutview(request):
	logout(request)
	return HttpResponseRedirect(reverse('home'))


def func(request):
	colleges = Colleges.objects.all()
	nslides = len(colleges)
	params = {'range': range(1,nslides),'colleges': colleges}
	return render(request,'accounts/index.html',params)


	

def registerview(request):
	form = RegistrationForm(request.POST or None)
	
	if request.method=="POST":
	
		if form.is_valid():
			first_name = form.cleaned_data.get('first_name')
			last_name= form.cleaned_data.get('last_name')
			reg = form.cleaned_data.get("reg")
			mobile = form.cleaned_data.get("mobile")
			gender = form.cleaned_data.get("gender")
			college = form.cleaned_data.get("college")
			email = form.cleaned_data.get('email')
			username = form.cleaned_data.get("username")
			password  = form.cleaned_data.get('password ')
			cpassword  = form.cleaned_data.get('cpassword ')
			
			user, create = User.objects.get_or_create(
			
				first_name=first_name,
				last_name=last_name,
				username=username,
				email=email,

			)
			user.set_password(form.cleaned_data['password'])
			user.save()
			

			pro = Profile(reg=reg, mobile=mobile, college=college , gender=gender, user=user ,rated = 0)
			pro.save()

			messages.success(request, "Successfully Saved")
			context={
				"msg":"Successfully Registered!!"
			} 
			
			return render(request,'accounts/messagesdisplay.html',context)
	context = {
		'form':form,
	}
	return render(request, 'accounts/registration.html', context)



def givereview(request,id):
	id=int(id)
	print(id)
	profile = Profile.objects.filter(user_id=id)
	profile=profile[0]
	print(type(profile.rated))
	#print(profile.college)
	context = {
		'profile':profile.college,
	}
	if profile.rated == 1 :
		context={
			"msg":"Review Already Submitted!!"
		} 
		return render(request,'accounts/messagesdisplay.html',context)
	else :
		Profile.objects.filter(user_id=id).update(rated = 1 )
		
	return render(request,'accounts/review.html',context)


def reviewsview(request,colg):
	colg=str(colg)
	print(colg)
	
	if request.method == "POST":

		a1 = request.POST.get("a1")
		a2 = request.POST.get("a2")
		a3 = request.POST.get("a3")
		a4 = request.POST.get("a4")
		

		b1 = request.POST.get("b1")
		b2 = request.POST.get("b2")
		b3 = request.POST.get("b3")
		b4 = request.POST.get("b4")

		c1 = request.POST.get("c1")
		c2 = request.POST.get("c2")
		c3 = request.POST.get("c3")
		c4 = request.POST.get("c4")

		d1 = request.POST.get("d1")
		d2 = request.POST.get("d2")
		d3 = request.POST.get("d3")
		d4 = request.POST.get("d4")

		e1 = request.POST.get("e1")
		e2 = request.POST.get("e2")
		e3 = request.POST.get("e3")
		e4 = request.POST.get("e4")

		if  e1 == None :
			e1 = 0
		if  e2 == None :
			e2 = 0
		if  e3 == None :
			e3 = 0
		if  e4 == None :
			e4 = 0

		if  d1 == None :
			d1 = 0
		if  d2 == None :
			d2 = 0
		if  d3 == None :
			d3 = 0
		if  d4 == None :
			d4 = 0

		if  c1 == None :
			c1 = 0
		if  c2 == None :
			c2 = 0
		if  c3 == None :
			c3 = 0
		if  c4 == None :
			c4 = 0

		if  b1 == None :
			b1 = 0
		if  b2 == None :
			b2 = 0
		if  b3 == None :
			b3 = 0
		if  b4 == None :
			b4 = 0

		if  a1 == None :
			a1 = 0
		if  a2 == None :
			a2 = 0
		if  a3 == None :
			a3 = 0
		if  a4 == None :
			a4 = 0

		
		print(a1,a2,a3,a4)
		print(b1,b2,b3,b4)
		print(c1,c2,c3,c4)
		print(d1,d2,d3,d4)
		print(e1,e2,e3,e4)
		review = inputreviews.objects.filter(college=colg)
		review = review[0]
		print(review.infrastructure,review.Academics)
		
		a1 = int(a1)
		a2 = int(a2)
		a3 = int(a3)
		a4 = int(a4)

		b1 = int(b1)
		b2 = int(b2)
		b3 = int(b3)
		b4 = int(b4)

		c1 = int(c1)
		c2 = int(c2)
		c3 = int(c3)
		c4 = int(c4)

		d1 = int(d1)
		d2 = int(d2)
		d3 = int(d3)
		d4 = int(d4)

		

		e1 = int(e1)
		e2 = int(e2)
		e3 = int(e3)
		e4 = int(e4)
		n = review.No_of_reviews + 1
		infra = (((review.infrastructure/100)*n*20)+(a1+a2+a3+a4))/((n+1)*20)*100
		academic =  (((review.Academics/100)*n*20)+(b1+b2+b3+b4))/((n+1)*20)*100
		curr =  (((review.Curricular/100)*n*20)+(c1+c2+c3+c4))/((n+1)*20)*100
		placement = (((review.Placement/100)*n*20)+(d1+d2+d3+d4))/((n+1)*20)*100
		hostel = (((review.Hostel/100)*n*20)+(e1+e2+e3+e4))/((n+1)*20)*100

		
		avg = (infra + academic + curr + placement + hostel) / 5
		inputreviews.objects.filter(college=colg).update(infrastructure = infra, Academics = academic, Curricular = curr, Placement = placement, Hostel = hostel, No_of_reviews = n , Average = avg  )
		
		context={
			"msg":" Your Review Is Recorded!! Thanks for giving Review !!"
		} 
		return render(request,'accounts/messagesdisplay.html',context)
	return render(request,'accounts/index.html')







def graphviews(request):
	
	pos = [0]*10
	neg = [0]*10

	all_data = inputreviews.objects.values_list('college', 'Average')
	print(all_data)
	for i in range(len(all_data)):
		if all_data[i][0] == 'NIT Agartala':
			pos[0] = all_data[i][1]
			neg[0] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Allahabad':
			pos[1] = all_data[i][1]
			neg[1] = 100 - all_data[i][1]

		elif all_data[i][0]== 'NIT Bhopal':
			pos[2] = all_data[i][1]
			neg[2] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Calicut':
			pos[3] = all_data[i][1]
			neg[3] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Jamshedpur':
			pos[4] = all_data[i][1]
			neg[4] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Kurukshetra':
			pos[5] = all_data[i][1]
			neg[5] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Raipur':
			pos[6] = all_data[i][1]
			neg[6] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Surathkal':
			pos[7] = all_data[i][1]
			neg[7] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Tiruchirappalli':
			pos[8] = all_data[i][1]
			neg[8] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Warangal':
			pos[9] = all_data[i][1]
			neg[9] = 100 - all_data[i][1]


	n = 10
	ind = np.arange(n)    # the x locations for the groups
	width = 0.55      # the width of the bars: can also be len(x) sequence

	
	fig, ax = plt.subplots(figsize=(8,7))
	ax.bar(ind, pos, width,color='green')
	ax.bar(ind,neg,width,bottom=pos,color='red')
	ax.set(ylabel ='Level of measurement', title = 'Analysis of various NITs ')
	ax.set_xticks(ind)
	ax.set_xticklabels(['NIT Agartala','NIT Allahabad','NIT Bhopal','NIT Calicut', 'NIT Jamshedpur', 'NIT Kurukshetra', 'NIT Raipur', 
		'NIT Surathkal','NIT Tiruchirappalli','NIT Warangal'],rotation=40)
	ax.set_xticks(ind,(	))
	ax.grid()

	FigureCanvas(fig)
	buf = io.BytesIO()
	plt.savefig(buf, format='png')
	plt.close(fig)
	response = HttpResponse(buf.getvalue(), content_type='image/png')
	return response







def graphsviews(request,colg):
	colg = str(colg)

	pos = [0]*5
	neg = [0]*5

	all_data = inputreviews.objects.filter(college=colg)
	all_data = all_data[0]
	#print(all_data)
	n = all_data.No_of_reviews
	pos[0] = all_data.infrastructure
	neg[0] = 100 - all_data.infrastructure


	pos[1] = all_data.Academics
	neg[1] = 100- all_data.Academics


	pos[2] = all_data.Placement
	neg[2] = 100 - all_data.Placement

	pos[3] = all_data.Hostel
	neg[3] = 100- all_data.Hostel

	pos[4] = all_data.Curricular
	neg[4] = 100 - all_data.Curricular


	n = 5
	ind = np.arange(n)    # the x locations for the groups
	width = 0.45      # the width of the bars: can also be len(x) sequence

	
	fig, ax = plt.subplots()
	ax.bar(ind, pos, width,color='green')
	ax.bar(ind,neg,width,bottom=pos,color='red')
	ax.set(ylabel ='Level of measurement', title = 'Analysis of '+colg)
	ax.set_xticks(ind)
	ax.set_xticklabels(['Infrastructure','Academics','Placements','Hostels', 'Extra-Curricular'])
	ax.set_xticks(ind,(	))
	ax.grid()

	FigureCanvas(fig)
	buf = io.BytesIO()
	plt.savefig(buf, format='png')
	plt.close(fig)
	response = HttpResponse(buf.getvalue(), content_type='image/png')
	return response











def placementviews(request):
	print("placement graph")
	pos = [0]*10
	neg = [0]*10

	all_data = inputreviews.objects.values_list('college', 'Placement')
	print(all_data)
	for i in range(len(all_data)):
		if all_data[i][0] == 'NIT Agartala':
			pos[0] = all_data[i][1]
			neg[0] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Allahabad':
			pos[1] = all_data[i][1]
			neg[1] = 100 - all_data[i][1]

		elif all_data[i][0]== 'NIT Bhopal':
			pos[2] = all_data[i][1]
			neg[2] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Calicut':
			pos[3] = all_data[i][1]
			neg[3] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Jamshedpur':
			pos[4] = all_data[i][1]
			neg[4] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Kurukshetra':
			pos[5] = all_data[i][1]
			neg[5] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Raipur':
			pos[6] = all_data[i][1]
			neg[6] = 100 - all_data[i][1]

		elif all_data[i][0] == 'NIT Surathkal':
			pos[7] = all_data[i][1]
			neg[7] = 100 - all_data[i][1]

src/templates/accounts/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>NIT REVIEW SYSTEM</title>

    <link rel="stylesheet" type="text/css" href="{% static 'accounts/index.css' %}">
  </head>
  <body>
  <div id="wrapper" >


    <div id="first" >
    <div id="div11" style="margin-top: 15px;">
      {% if user.is_authenticated %}
      <h1 >HELLO!!     {{ user.first_name}}</h1>
      <p style="margin-top: 30px;font-size: 1.4em"><i>Rate your college today!</i></p>
      {% else %}
      <h1 >NIT REVIEWS</h1>
      <p style="margin-top: 30px;font-size: 1.4em"><i>Rate your college today!</i></p>
      {% endif %}
 </div>


 <div id="menu">
 <div id="menu4">
  <ul>
     <li><a href="{% url 'home' %}">HOME</a></li>
      
     <li><a href="{% url 'accounts:graph' %}">ALL NITs</a></li>
     <li><a href="{% url 'accounts:placement' %}">PLACEMENTs</a></li>

  <li>
  <div class="dropdown">
  <button class="dropbtn"><b>SELECT NITs</b></button>
  <div class="dropdown-content">
  <a href="{% url 'accounts:graphs' colg='NIT Agartala'%}">NIT Agartala</a>
  <a href="{% url 'accounts:graphs' colg='NIT Allahabad'%}">NIT Allahabad</a>
  <a href="{% url 'accounts:graphs' colg='NIT Bhopal'%}">NIT Bhopal</a>
  <a href="{% url 'accounts:graphs' colg='NIT Calicut'%}">NIT Calicut</a>
  <a href="{% url 'accounts:graphs' colg='NIT Jamshedpur'%}">NIT Jamshedpur</a>
  <a href="{% url 'accounts:graphs' colg='NIT Kurukshetra'%}">NIT Kurukshetra</a>
  <a href="{% url 'accounts:graphs' colg='NIT Raipur'%}">NIT Raipur</a>
  <a href="{% url 'accounts:graphs' colg='NIT Surathkal'%}">NIT Surathkal</a>
  <a href="{% url 'accounts:graphs' colg='NIT Tiruchirappalli'%}">NIT Tiruchirappalli</a>
  <a href="{% url 'accounts:graphs' colg='NIT Warangal'%}">NIT Warangal</a>
  </div>
</div>
</li>
 {% if user.is_authenticated %}

     <li><a href="{% url 'accounts:review' id=user.id %}">GIVE REVIEW</a></li>
     {% else %}
     <li><a href="{% url 'accounts:register' %}">SIGN UP</a></li>
     {% endif %}
{% if user.is_authenticated %}
     <li><a href="{% url 'accounts:logout' %}">LOGOUT</a></li>
{% else %}
     <li><a href="{% url 'accounts:login' %}">LOGIN</a></li>
{% endif %}

 </ul>
</div>
</div>
</div>






<div id="div1">

<div id="slider" >
<div class="container"  style="margin-right:100px;height:400px; margin-left:100px;width: 1200px; ">
  
<div id="demo" class="carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>

       {% for i in range %}
      <li data-target="#demo" data-slide-to="{{i}}" ></li>
      {% endfor %}
    </ul>

    <!--Slideshow starts here -->
    <div class="container carousel-inner no-padding"  style="  margin-top: 0px; margin-left: 0px; margin-right: 0px; margin-bottom: 0px;">

      <div class="carousel-item active">
        <div class="col-xs-3 col-sm-3 col-md-3">
      <div class="c" style=" ">
      <img src='/media/{{colleges.0.image}}' style="height:1200px; margin-left:-20px;" class="c-img-top" alt="...">
      </div>
    </div>


        {% for i in colleges|slice:"0:"%}
        <div class="col-xs-3 col-sm-3 col-md-3">
      <div class="c" style="  margin-left: -20px; ">
      <img src='/media/{{i.image}}' class="c-img-top" alt="...">
      </div>
    </div>
        {% if forloop.counter|divisibleby:1 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}

        {% endfor %}
    </div>



</div>
  </div>
</div>
</div>
</div>

<div id="footer">
  <p><i><marquee>
Reviews of the Colleges
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Reviews by the Students
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Reviews for the Students
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
NIT Review System allows students from different NIT'S to give feedbacks on diffrent aspects
and generates graph on that basis.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<h7>Visit Often for latest rankings...</h7></i></marquee></p>
</div>








<!-- left and right controls for the slide -->
<a class="carousel-control-prev" href="#demo" data-slide="prev">
  <span class="carousel-control-prev-icon"></span>
</a>
<a class="carousel-control-next" href="#demo" data-slide="next">
  <span class="carousel-control-next-icon"></span>
</a>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</div>
</body>
</html>

src/templates/accounts/login.html
<!--         <form action="." method="POST">
            {% csrf_token %}
			{{form.as_p|safe}}
		<br>		
		<button type='submit' class="btn btn-info">Login</button>
        </form>
    
     -->




<html>
<head>

<style>
#he{
position:relative;
height:50px;
width:100%;
background-color:#28004d;
}
.title{
color:white;
font-size:40px;
font-family:lucida console;
text-align:center;
}



</style>

</head>
<body>
<div id='he'>

<p class='title'>R E V I E W S</p>


</div>
</body>
</html><html>

<style>
body {
    background-image: url("/Media/accountss/images/notebook.jpg");
    background-repeat: no-repeat;
    background-position: right top;
   
}


#box
{
height:20px;
width:500px;
margin-left:10px;
float:right;

}

#1
{
font-family:TIMES NEW ROMAN;
font-size:54;
color:RED;
margin-right:50px;
text-align:left;
}

#a{
	background-color:#28004d;
	height:70px;
	width:100%; 
	font-family:segoe script;
	color:#133926;
	font-style:bold;
	font-size:24px;
	color: white;
}
#b{
	margin-top:20px;
	margin-left:70px;
	margin-right:70px;

	border-radius:10px;

	padding:30px;

 
  max-width: 600px;
  opacity:0.95;
  background-color:#f2f2f2;
	
}
body, html {
  height: 100%;
}

* {
  box-sizing: border-box;
}


  input {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  border: none;
  background:bfbfbf;
}

input:focus {
  background-color: #ddd;
  outline: none;
}
#bg{
  background-image: url("/media/accounts/images/notebook.jpg");
  height: 590px;

  
}

.btn {
  background-color: #80002a;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
</style>
</head>
<body>
<div id="bg">
<div id="a"> <center>"Rate your College!!" </center></div>
<center>
  
<div id="b" style="margin-top: 50px;">
      <form action="." method="POST">
            {% csrf_token %}
			{{form.as_p|safe}}
		<br>		
		<button type='submit' class="btn btn-info">Login</button>
        </form>

</div>
</div>
</center>
</body>

</html>